# Generated by Django 5.2.5 on 2025-08-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fixture_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
